import re
import tkinter as tk
from tkinter import scrolledtext
from tkinter import messagebox

# -----------------------------------------------------------------------------
# 1) TOKEN DEFINITION
# -----------------------------------------------------------------------------

TOKEN_SPECIFICATIONS = [
    # (regex_pattern, token_type)
    (r'//.*',            'COMMENT'),       # Single-line comment
    (r'\bprogram\b',     'PROGRAM'),       # program keyword
    (r'\bend_program\b', 'END_PROGRAM'),   # end_program keyword
    (r'\bif\b',          'IF'),            # if keyword
    (r'\bend_if\b',      'END_IF'),        # end_if keyword
    (r'\bloop\b',        'LOOP'),          # loop keyword
    (r'\bend_loop\b',    'END_LOOP'),      # end_loop keyword
    (r'\b[0-9]+\b',      'NUMBER'),        # Numeric literal
    (r'\b[a-zA-Z]\w*\b', 'IDENTIFIER'),    # Alphanumeric identifier (not starting with digit)
    (r'==',              'EQ'),            # ==
    (r'!=',              'NEQ'),           # !=
    (r'>=',              'GE'),            # >=
    (r'<=',              'LE'),            # <=
    (r'>',               'GT'),            # >
    (r'<',               'LT'),            # <
    (r'\+\+',            'INC'),           # Not in spec, but just an example (if needed)
    (r'\+',              'PLUS'),          # +
    (r'-',               'MINUS'),         # -
    (r'\*',              'MUL'),           # *
    (r'/',               'DIV'),           # /
    (r'%',               'MOD'),           # %
    (r'&&',              'AND'),           # &&
    (r'\|\|',            'OR'),            # ||
    (r'=',               'ASSIGN'),        # =
    (r'\(',              'LPAREN'),        # (
    (r'\)',              'RPAREN'),        # )
    (r':',               'COLON'),         # :
    (r';',               'SEMICOLON'),     # ;
    (r'\s+',             None),            # Whitespace (no token returned)
]

class Token:
    """
    A simple Token structure with type and value.
    """
    def __init__(self, ttype, value, position):
        self.type = ttype
        self.value = value
        self.position = position  # (line, column) or character index

    def __repr__(self):
        return f"Token({self.type}, {self.value}, pos={self.position})"

# -----------------------------------------------------------------------------
# 2) LEXER IMPLEMENTATION
# -----------------------------------------------------------------------------

class Lexer:
    """
    A simple regex-based lexer for the specified language.
    """
    def __init__(self, text):
        self.text = text
        self.tokens = []
        self.position = 0
        self.create_tokens()

    def create_tokens(self):
        # Combine all token regexes into one big pattern with named capture groups or just sequentially.
        # We'll apply them in a loop, scanning from left to right.
        idx = 0
        while idx < len(self.text):
            match_found = False
            for pattern, token_type in TOKEN_SPECIFICATIONS:
                regex = re.compile(pattern)
                match = regex.match(self.text, idx)
                if match:
                    match_text = match.group(0)
                    if token_type and token_type != 'COMMENT':
                        # We'll store non-ignored tokens
                        self.tokens.append(Token(token_type, match_text, idx))
                    idx += len(match_text)
                    match_found = True
                    break
            if not match_found:
                # Unknown or illegal token
                raise ValueError(f"Illegal character at index {idx}: '{self.text[idx]}'")
        # Append an end-of-input marker if desired
        self.tokens.append(Token('EOF', 'EOF', idx))

    def peek(self):
        """ Look at the current token without consuming it. """
        if self.position < len(self.tokens):
            return self.tokens[self.position]
        return None

    def advance(self):
        """ Consume and return the current token, then advance position. """
        token = self.peek()
        self.position += 1
        return token

# -----------------------------------------------------------------------------
# 3) RECURSIVE DESCENT PARSER
# -----------------------------------------------------------------------------

class ParserError(Exception):
    """Custom exception for parser errors."""
    pass

class Parser:
    """
    Recursive Descent Parser that uses the tokens generated by the Lexer.
    We'll build an Abstract Syntax Tree (AST) or just parse to confirm correctness.
    """
    def __init__(self, lexer):
        self.lexer = lexer
        self.current_token = self.lexer.peek()

    def error(self, message):
        raise ParserError(f"Parser error at position {self.current_token.position}: {message}")

    def eat(self, token_type):
        # Ensure current token matches token_type, then move to the next
        if self.current_token.type == token_type:
            self.current_token = self.lexer.advance()
        else:
            self.error(f"Expected token type {token_type} but got {self.current_token.type}")

    def parse(self):
        """
        Entry point: parse a 'program' structure as per grammar:
        PROGRAM -> 'program' STATEMENTS 'end_program'
        """
        self.parseProgram()
        # If we didn't consume the entire token stream, there might be trailing garbage
        if self.current_token.type != 'EOF':
            self.error("Extra tokens after end of program.")
        return True  # If no error was raised, parsing was successful

    # Grammar production: program -> 'program' STATEMENTS 'end_program'
    def parseProgram(self):
        if self.current_token.type == 'PROGRAM':
            self.eat('PROGRAM')
            self.parseStatements()
            if self.current_token.type == 'END_PROGRAM':
                self.eat('END_PROGRAM')
            else:
                self.error("Missing 'end_program' at the end.")
        else:
            self.error("Program must start with 'program'")

    # statements -> { statement }
    def parseStatements(self):
        # parse zero or more statements until we see 'end_program', 'END_IF', 'END_LOOP' or 'EOF'
        # because those tokens can signal the end of a statement block
        stop_types = {'END_PROGRAM', 'END_IF', 'END_LOOP', 'EOF'}
        while self.current_token.type not in stop_types:
            self.parseStatement()

    # statement -> assignment ';' | if_statement | loop_statement
    def parseStatement(self):
        ttype = self.current_token.type
        if ttype == 'IDENTIFIER':
            # This must be an assignment: <identifier> '=' expression ';'
            self.parseAssignment()
            self.eat('SEMICOLON')
        elif ttype == 'IF':
            self.parseIfStatement()
        elif ttype == 'LOOP':
            self.parseLoopStatement()
        else:
            self.error(f"Unexpected token in statement: {ttype}")

    # assignment -> identifier '=' expression
    def parseAssignment(self):
        # We assume we've already seen an 'IDENTIFIER'
        var_token = self.current_token
        self.eat('IDENTIFIER')
        self.eat('ASSIGN')
        self.parseExpression()

    # if_statement -> 'if' '(' logic_expr ')' statements 'end_if'
    def parseIfStatement(self):
        self.eat('IF')
        self.eat('LPAREN')
        self.parseLogicExpr()
        self.eat('RPAREN')
        self.parseStatements()
        self.eat('END_IF')

    # loop_statement -> 'loop' '(' identifier '=' (identifier|number) ':' (identifier|number) ')' statements 'end_loop'
    def parseLoopStatement(self):
        self.eat('LOOP')
        self.eat('LPAREN')
        self.eat('IDENTIFIER')  # loop variable
        self.eat('ASSIGN')
        if self.current_token.type in ('IDENTIFIER', 'NUMBER'):
            self.eat(self.current_token.type)
        else:
            self.error("Expected IDENTIFIER or NUMBER in loop start value.")
        self.eat('COLON')
        if self.current_token.type in ('IDENTIFIER', 'NUMBER'):
            self.eat(self.current_token.type)
        else:
            self.error("Expected IDENTIFIER or NUMBER in loop end value.")
        self.eat('RPAREN')
        self.parseStatements()
        self.eat('END_LOOP')

    # logic_expr -> comparison { ('&&' | '||') comparison }
    def parseLogicExpr(self):
        self.parseComparison()
        while self.current_token.type in ('AND', 'OR'):
            self.eat(self.current_token.type)
            self.parseComparison()

    # comparison -> (IDENTIFIER|NUMBER) ( '==' | '!=' | '>' | '<' | '>=' | '<=' ) (IDENTIFIER|NUMBER)
    def parseComparison(self):
        if self.current_token.type not in ('IDENTIFIER','NUMBER'):
            self.error("Expected IDENTIFIER or NUMBER in comparison.")
        self.eat(self.current_token.type)

        if self.current_token.type not in ('EQ','NEQ','GT','LT','GE','LE'):
            self.error("Expected a comparison operator (==, !=, >, <, >=, <=).")
        self.eat(self.current_token.type)

        if self.current_token.type not in ('IDENTIFIER','NUMBER'):
            self.error("Expected IDENTIFIER or NUMBER in comparison.")
        self.eat(self.current_token.type)

    # expression -> term { ('+'|'-') term }
    def parseExpression(self):
        self.parseTerm()
        while self.current_token.type in ('PLUS','MINUS'):
            self.eat(self.current_token.type)
            self.parseTerm()

    # term -> factor { ('*'|'/'|'%') factor }
    def parseTerm(self):
        self.parseFactor()
        while self.current_token.type in ('MUL','DIV','MOD'):
            self.eat(self.current_token.type)
            self.parseFactor()

    # factor -> '(' expression ')' | IDENTIFIER | NUMBER
    def parseFactor(self):
        ttype = self.current_token.type
        if ttype == 'LPAREN':
            self.eat('LPAREN')
            self.parseExpression()
            self.eat('RPAREN')
        elif ttype in ('IDENTIFIER', 'NUMBER'):
            self.eat(ttype)
        else:
            self.error("Expected '(', IDENTIFIER, or NUMBER in factor.")

# -----------------------------------------------------------------------------
# 4) TKINTER GUI
# -----------------------------------------------------------------------------

class ParserGUI:
    def __init__(self, master):
        self.master = master
        self.master.title("Simple Recursive Descent Parser GUI")

        # Text area for input
        self.text_area = scrolledtext.ScrolledText(master, wrap=tk.WORD, width=60, height=20)
        self.text_area.pack(padx=10, pady=10)

        # Frame for buttons
        button_frame = tk.Frame(master)
        button_frame.pack(pady=5)

        self.parse_button = tk.Button(button_frame, text="Parse", command=self.parse_input)
        self.parse_button.pack(side=tk.LEFT, padx=5)

        self.clear_button = tk.Button(button_frame, text="Clear", command=self.clear_text)
        self.clear_button.pack(side=tk.LEFT, padx=5)

    def parse_input(self):
        source_code = self.text_area.get("1.0", tk.END)
        try:
            lexer = Lexer(source_code)
            parser = Parser(lexer)
            parser.parse()
            messagebox.showinfo("Result", "Parsing succeeded! No errors found.")
        except (ParserError, ValueError) as e:
            messagebox.showerror("Error", str(e))

    def clear_text(self):
        self.text_area.delete("1.0", tk.END)

# -----------------------------------------------------------------------------
# Main entry point
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    root = tk.Tk()
    gui = ParserGUI(root)
    root.mainloop()
